version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: rag_auth_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ragdb
      MYSQL_USER: raguser
      MYSQL_PASSWORD: ragpass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
